In [1]:
import pandas as pd
import numpy as np

/Users/ansomin/opt/anaconda3/envs/umich/lib/python3.10/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [52]:
df = pd.read_csv("safety_combined_dataset.csv")

In [53]:
df.columns

Index(['make_id', 'make', 'model_id', 'model', 'trim_id', 'year', 'trim',
       'trim_description', 'trim_msrp', 'trim_invoice', 'trim_created',
       'trim_modified', 'engine_id', 'engine_type', 'engine_fuel_type',
       'engine_cylinders', 'engine_size', 'engine_horsepower_hp',
       'engine_horsepower_rpm', 'engine_torque_ft_lbs', 'engine_torque_rpm',
       'engine_valves', 'engine_valve_timing', 'engine_cam_type',
       'drive_train', 'engine_transmission', 'body_id', 'body_type',
       'body_doors', 'body_seats', 'body_length', 'body_width', 'body_height',
       'body_wheel_base', 'body_front_track', 'body_rear_track',
       'body_ground_clearance', 'body_cargo_capacity',
       'body_max_cargo_capacity', 'body_curb_weight', 'body_gross_weight',
       'body_max_payload', 'body_max_towing_capacity', 'mileage_id',
       'mileage_fuel_tank_capacity', 'mileage_combined_mpg',
       'mileage_epa_city_mpg', 'mileage_epa_highway_mpg', 'mileage_range_city',
       'mileage_range_highway', 'mileage_epa_combined_mpg_electric',
       'mileage_epa_city_mpg_electric', 'mileage_epa_highway_mpg_electric',
       'mileage_range_electric', 'mileage_epa_kwh_100_mi_electric',
       'mileage_epa_time_to_charge_hr_240v_electric',
       'mileage_battery_capacity_electric', 'min_price', 'median_price',
       'accident_safety_rating'],
      dtype='object')

In [7]:
df.head(2)

,make_id,make,model_id,model,trim_id,year,trim,trim_description,trim_msrp,trim_invoice,...,mileage_epa_combined_mpg_electric,mileage_epa_city_mpg_electric,mileage_epa_highway_mpg_electric,mileage_range_electric,mileage_epa_kwh_100_mi_electric,mileage_epa_time_to_charge_hr_240v_electric,mileage_battery_capacity_electric,min_price,median_price,accident_safety_rating
0,1,acura,97,ilx,6292,2020,Base,4dr Sedan (2.4L 4cyl 8AM),25900,24617,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995,23569,5.0
1,1,acura,97,ilx,6295,2020,Premium and A-SPEC Packages,Premium and A-SPEC Packages 4dr Sedan (2.4L 4c...,29750,28264,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995,23569,5.0

In [54]:
df.loc[df["median_price"] == 0, "median_price"] = np.nan
df.loc[df["min_price"] == 0, "min_price"] = np.nan

In [55]:
df["min_price"].value_counts()

min_price
16669.0     59
11434.0     56
15361.0     54
12443.0     53
13163.0     50
            ..
188919.0     1
14480.0      1
119984.0     1
121809.0     1
283905.0     1
Name: count, Length: 1792, dtype: int64

In [56]:
df["median_price"].value_counts()

median_price
18462.0     56
10568.0     55
24994.0     54
18417.0     50
27762.0     50
            ..
242348.0     1
10819.0      1
32458.0      1
23039.0      1
120027.0     1
Name: count, Length: 1803, dtype: int64

In [57]:
# null value imputations
df['min_price'] = df['min_price'].fillna(df.groupby(['make','model','year'])['min_price'].transform('median'))
df['min_price'] = df['min_price'].fillna(df.groupby(['make','model'])['min_price'].transform('median'))
# df['min_price'] = df['min_price'].fillna(df.groupby(['make'])['min_price'].transform('median'))

In [58]:
df['median_price'] = df['median_price'].fillna(df.groupby(['make','model','year'])['median_price'].transform('median'))
df['median_price'] = df['median_price'].fillna(df.groupby(['make','model'])['median_price'].transform('median'))
# df['median_price'] = df['median_price'].fillna(df.groupby(['make'])['median_price'].transform('median'))

In [60]:
df['accident_safety_rating'] = df['accident_safety_rating'].fillna(df.groupby(['make','model','year'])['accident_safety_rating'].transform('median'))
df['accident_safety_rating'] = df['accident_safety_rating'].fillna(df.groupby(['make','model'])['accident_safety_rating'].transform('median'))

In [62]:
print(df.min_price.isnull().sum())
print(df.median_price.isnull().sum())
print(df.accident_safety_rating.isnull().sum())

3739
3739
7689

In [63]:
df

,make_id,make,model_id,model,trim_id,year,trim,trim_description,trim_msrp,trim_invoice,...,mileage_epa_combined_mpg_electric,mileage_epa_city_mpg_electric,mileage_epa_highway_mpg_electric,mileage_range_electric,mileage_epa_kwh_100_mi_electric,mileage_epa_time_to_charge_hr_240v_electric,mileage_battery_capacity_electric,min_price,median_price,accident_safety_rating
0,1,acura,97,ilx,6292,2020,Base,4dr Sedan (2.4L 4cyl 8AM),25900,24617,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995.0,23569.0,5.0
1,1,acura,97,ilx,6295,2020,Premium and A-SPEC Packages,Premium and A-SPEC Packages 4dr Sedan (2.4L 4c...,29750,28264,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995.0,23569.0,5.0
2,1,acura,97,ilx,6293,2020,Premium Package,Premium Package 4dr Sedan (2.4L 4cyl 8AM),27750,26370,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995.0,23569.0,5.0
3,1,acura,97,ilx,6296,2020,Technology and A-SPEC Packages,Technology and A-SPEC Packages 4dr Sedan (2.4L...,31650,30064,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995.0,23569.0,5.0
4,1,acura,97,ilx,6294,2020,Technology Package,Technology Package 4dr Sedan (2.4L 4cyl 8AM),29650,28169,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995.0,23569.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17657,23,volvo,589,xc70,23952,2015,3.2,3.2 4dr Wagon AWD (3.2L 6cyl 6A),37550,35297,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023.0,14353.0,NaN
17658,23,volvo,589,xc70,23949,2015,T5 Drive-E,T5 Drive-E 4dr Wagon w/Prod. End 5/14 (2.0L 4c...,35400,33276,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023.0,14353.0,NaN
17659,23,volvo,589,xc70,23950,2015,T5 Drive-E,T5 Drive-E 4dr Wagon (2.0L 4cyl Turbo 8A),36050,33887,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023.0,14353.0,NaN
17660,23,volvo,589,xc70,23954,2015,T6,T6 4dr Wagon AWD (3.0L 6cyl Turbo 6A),42050,39527,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023.0,14353.0,NaN
17661,23,volvo,589,xc70,23953,2015,T6,T6 4dr Wagon AWD w/Prod. End 5/14 (3.0L 6cyl T...,41800,39292,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023.0,14353.0,NaN

In [71]:
df.min_price.isnull().sum()

0

In [72]:
df= df.dropna(subset=['min_price','median_price','accident_safety_rating'])

In [74]:
df.columns

Index(['make_id', 'make', 'model_id', 'model', 'trim_id', 'year', 'trim',
       'trim_description', 'trim_msrp', 'trim_invoice', 'trim_created',
       'trim_modified', 'engine_id', 'engine_type', 'engine_fuel_type',
       'engine_cylinders', 'engine_size', 'engine_horsepower_hp',
       'engine_horsepower_rpm', 'engine_torque_ft_lbs', 'engine_torque_rpm',
       'engine_valves', 'engine_valve_timing', 'engine_cam_type',
       'drive_train', 'engine_transmission', 'body_id', 'body_type',
       'body_doors', 'body_seats', 'body_length', 'body_width', 'body_height',
       'body_wheel_base', 'body_front_track', 'body_rear_track',
       'body_ground_clearance', 'body_cargo_capacity',
       'body_max_cargo_capacity', 'body_curb_weight', 'body_gross_weight',
       'body_max_payload', 'body_max_towing_capacity', 'mileage_id',
       'mileage_fuel_tank_capacity', 'mileage_combined_mpg',
       'mileage_epa_city_mpg', 'mileage_epa_highway_mpg', 'mileage_range_city',
       'mileage_range_highway', 'mileage_epa_combined_mpg_electric',
       'mileage_epa_city_mpg_electric', 'mileage_epa_highway_mpg_electric',
       'mileage_range_electric', 'mileage_epa_kwh_100_mi_electric',
       'mileage_epa_time_to_charge_hr_240v_electric',
       'mileage_battery_capacity_electric', 'min_price', 'median_price',
       'accident_safety_rating'],
      dtype='object')

In [73]:
df.to_csv("updated_car_info_and_safety_ratings.csv", index=False)