In [1]:
import pandas as pd
import io
from kbb import Cars
import time

In [ ]:
car_info = pd.read_csv("updated_car_info_and_safety_ratings2.csv")
car_info["image"] = None
car_info["expert_score"] = None
car_info["consumer_score"] = None

make = ""
model = ""
year = 1111
results = {}
for index, row in car_info.iterrows():
    make2 = row["make"]
    model2 = row["model"]
    year2 = row["year"]

    if make == make2 and model == model2 and year == year2:
        print("same car")
        car_info.loc[index, results.keys()] = results.values()
        continue
    else:
        print(make2, model2, year2)
        car = Cars(make2, model2, year2)
        results = car.get_car()

        car_info.loc[index, results.keys()] = results.values()
        make = make2
        model = model2
        year = year2

car_info.to_csv("combined.csv", index=False)

In [ ]:
images = car_info.image.unique()
images2 = {}
count = 1
for image in images:
    images2[image] = count
    count += 1

images2

In [ ]:
car_info["image_id"] = None

def set_image_id(row):
    row["image_id"] = images2[row["image"]]
    return row

car_info2 = car_info.apply(set_image_id, axis=1)

# car_info.to_csv("combined.csv", index=False)
car_info2

In [ ]:
car_info2.to_csv("combined.csv", index=False)

----------------------

In [3]:
car_info = pd.read_csv("combined.csv")
car_info[car_info["make"] == "tesla"][["engine_type", "drive_train", "mileage_fuel_tank_capacity", "mileage_combined_mpg", "mileage_epa_combined_mpg_electric", "mileage_battery_capacity_electric"]]

,engine_type,drive_train,mileage_fuel_tank_capacity,mileage_combined_mpg,mileage_epa_combined_mpg_electric,mileage_battery_capacity_electric
1204,electric,AWD,NaN,NaN,121.0,NaN
1205,electric,AWD,NaN,NaN,113.0,NaN
1206,electric,RWD,NaN,NaN,141.0,NaN
1207,electric,RWD,NaN,NaN,NaN,NaN
1208,electric,AWD,NaN,NaN,121.0,NaN
1209,electric,AWD,NaN,NaN,121.0,NaN
2745,electric,RWD,NaN,NaN,130.0,NaN
2746,electric,AWD,NaN,NaN,116.0,NaN
2747,electric,RWD,NaN,NaN,123.0,NaN
2748,electric,AWD,NaN,NaN,116.0,NaN
2749,electric,RWD,NaN,NaN,131.0,NaN
2750,electric,RWD,NaN,NaN,133.0,NaN
4285,electric,RWD,NaN,NaN,130.0,80.0
4286,electric,AWD,NaN,NaN,116.0,NaN
4287,electric,RWD,NaN,NaN,123.0,NaN
4288,electric,AWD,NaN,NaN,116.0,NaN
5862,electric,RWD,NaN,NaN,126.0,80.0

In [4]:
car_info[car_info["make"] == "honda"][["engine_type", "drive_train", "mileage_fuel_tank_capacity", "mileage_combined_mpg", "mileage_epa_combined_mpg_electric", "mileage_battery_capacity_electric"]]

,engine_type,drive_train,mileage_fuel_tank_capacity,mileage_combined_mpg,mileage_epa_combined_mpg_electric,mileage_battery_capacity_electric
592,gas,FWD,14.8,33.0,NaN,NaN
593,gas,FWD,14.8,27.0,NaN,NaN
594,gas,FWD,14.8,33.0,NaN,NaN
595,gas,FWD,14.8,33.0,NaN,NaN
596,gas,FWD,14.8,30.0,NaN,NaN
...,...,...,...,...,...,...
8382,gas,4WD,21.0,20.0,NaN,NaN
8383,gas,4WD,21.0,20.0,NaN,NaN
8384,gas,FWD,21.0,21.0,NaN,NaN
8385,gas,FWD,21.0,21.0,NaN,NaN
8386,gas,4WD,21.0,20.0,NaN,NaN

In [5]:
car_info[car_info["engine_type"] == "hybrid"][["engine_type", "drive_train", "mileage_fuel_tank_capacity", "mileage_combined_mpg", "mileage_epa_combined_mpg_electric", "mileage_battery_capacity_electric"]]

,engine_type,drive_train,mileage_fuel_tank_capacity,mileage_combined_mpg,mileage_epa_combined_mpg_electric,mileage_battery_capacity_electric
15,hybrid,AWD,19.4,27.0,NaN,NaN
16,hybrid,AWD,19.4,27.0,NaN,NaN
26,hybrid,AWD,15.1,28.0,NaN,NaN
421,hybrid,AWD,NaN,40.0,NaN,NaN
422,hybrid,FWD,NaN,41.0,NaN,NaN
...,...,...,...,...,...,...
8889,hybrid,FWD,9.5,50.0,NaN,NaN
8890,hybrid,FWD,9.5,50.0,NaN,NaN
8891,hybrid,FWD,9.5,50.0,NaN,NaN
8892,hybrid,FWD,9.5,50.0,NaN,NaN
9093,hybrid,FWD,11.9,45.0,NaN,NaN

In [6]:
car_info.engine_type.value_counts()

engine_type
gas                  7929
flex-fuel (FFV)       658
hybrid                287
diesel                115
plug-in hybrid         73
electric               70
mild hybrid            56
natural gas (CNG)       2
Name: count, dtype: int64

In [8]:
car_info.drive_train.value_counts()

drive_train
FWD    3953
AWD    2450
RWD    1570
4WD    1217
Name: count, dtype: int64

In [9]:
drive_trains = car_info.drive_train.unique()
drive_trains2 = {}
count = 1
for drive_train in drive_trains:
    drive_trains2[drive_train] = count
    count += 1

engine_types = car_info.engine_type.unique()
engine_types2 = {}
count = 1
for engine_type in engine_types:
    engine_types2[engine_type] = count
    count += 1

In [11]:
car_info["drivetrain_id"] = None
car_info["enginetype_id"] = None



def set_drivetrain_enginetype_id(row):
    row["drivetrain_id"] = drive_trains2[row["drive_train"]]
    row["enginetype_id"] = engine_types2[row["engine_type"]]
    return row

car_info2 = car_info.apply(set_drivetrain_enginetype_id, axis=1)
car_info2

,make_id,make,model_id,model,trim_id,year,trim,trim_description,trim_msrp,trim_invoice,...,mileage_battery_capacity_electric,min_price,median_price,accident_safety_rating,image,expert_score,consumer_score,image_id,drivetrain_id,enginetype_id
0,1,acura,1,ilx,1,2020,Base,4dr Sedan (2.4L 4cyl 8AM),25900,24617,...,NaN,19466.0,23524.0,5.0,https://file.kelleybluebookimages.com/kbb/base...,4.4,4.3,1,1,1
1,1,acura,1,ilx,2,2020,Premium and A-SPEC Packages,Premium and A-SPEC Packages 4dr Sedan (2.4L 4c...,29750,28264,...,NaN,19466.0,23524.0,5.0,https://file.kelleybluebookimages.com/kbb/base...,4.4,4.3,1,1,1
2,1,acura,1,ilx,3,2020,Premium Package,Premium Package 4dr Sedan (2.4L 4cyl 8AM),27750,26370,...,NaN,19466.0,23524.0,5.0,https://file.kelleybluebookimages.com/kbb/base...,4.4,4.3,1,1,1
3,1,acura,1,ilx,4,2020,Technology and A-SPEC Packages,Technology and A-SPEC Packages 4dr Sedan (2.4L...,31650,30064,...,NaN,19466.0,23524.0,5.0,https://file.kelleybluebookimages.com/kbb/base...,4.4,4.3,1,1,1
4,1,acura,1,ilx,5,2020,Technology Package,Technology Package 4dr Sedan (2.4L 4cyl 8AM),29650,28169,...,NaN,19466.0,23524.0,5.0,https://file.kelleybluebookimages.com/kbb/base...,4.4,4.3,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9185,26,volvo,178,xc60,650,2015,T6 R-Design Platinum,T6 R-Design Platinum 4dr SUV AWD w/Prod. End 6...,49800,46812,...,NaN,6981.0,10814.0,5.0,https://file.kelleybluebookimages.com/kbb/base...,3.4,4.4,1038,2,1
9186,26,volvo,178,xc60,650,2015,T6 R-Design Platinum,T6 R-Design Platinum 4dr SUV AWD (3.0L 6cyl Tu...,51050,47987,...,NaN,6981.0,10814.0,5.0,https://file.kelleybluebookimages.com/kbb/base...,3.4,4.4,1038,2,1
9187,26,volvo,178,xc60,971,2015,T6 R-Design Premier Plus,T6 R-Design Premier Plus 4dr SUV AWD w/Prod. E...,47200,44368,...,NaN,6981.0,10814.0,5.0,https://file.kelleybluebookimages.com/kbb/base...,3.4,4.4,1038,2,1
9188,26,volvo,178,xc60,972,2015,T6 Volvo Ocean Race,T6 Volvo Ocean Race 4dr SUV AWD (3.0L 6cyl Tur...,43850,41219,...,NaN,6981.0,10814.0,5.0,https://file.kelleybluebookimages.com/kbb/base...,3.4,4.4,1038,2,1
9189,26,volvo,178,xc60,973,2015,T6 Volvo Ocean Race Platinum,T6 Volvo Ocean Race Platinum 4dr SUV AWD (3.0L...,48250,45355,...,NaN,6981.0,10814.0,5.0,https://file.kelleybluebookimages.com/kbb/base...,3.4,4.4,1038,2,1

------------------

In [13]:
all_mm = pd.read_csv("all_makes_models.csv")
all_mm

,make,model,year,trim,fuel_type,drivetrain,city_fuel_economy,hwy_fuel_economy,comb_fuel_economy,transmission_type,min_price,med_price,image,expert_score,consumer_score
0,acura,rdx,2024,RDX SH-AWD,Gas,AWD,21,27,23,Automatic,45700,51350,https://file.kelleybluebookimages.com/kbb/base...,4.6,3.9
1,acura,rdx,2024,RDX SH-AWD w/Technology Pkg,Gas,AWD,21,27,23,Automatic,48350,51350,https://file.kelleybluebookimages.com/kbb/base...,4.6,3.9
2,acura,rdx,2024,RDX SH-AWD w/A-Spec Pkg,Gas,AWD,21,27,23,Automatic,51350,51350,https://file.kelleybluebookimages.com/kbb/base...,4.6,3.9
3,acura,rdx,2024,RDX SH-AWD w/Advance Pkg,Gas,AWD,21,27,23,Automatic,53500,51350,https://file.kelleybluebookimages.com/kbb/base...,4.6,3.9
4,acura,rdx,2024,RDX SH-AWD w/A-Spec & Advance Pkgs,Gas,AWD,21,26,23,Automatic,55500,51350,https://file.kelleybluebookimages.com/kbb/base...,4.6,3.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19838,volvo,xc70,2010,Wagon 4D,Gas,AWD,16,22,18,Automatic,6685,6990,https://file.kelleybluebookimages.com/kbb/base...,0.0,0.0
19839,volvo,xc70,2010,XC70 T6 Wagon 4D,Gas,AWD,16,21,18,Automatic,7295,6990,https://file.kelleybluebookimages.com/kbb/base...,0.0,0.0
19840,volvo,c30,2010,D,Gas,FWD,21,29,24,Manual,7597,7654,https://file.kelleybluebookimages.com/kbb/base...,0.0,0.0
19841,volvo,c30,2010,D,Gas,FWD,21,29,24,Manual,7712,7654,https://file.kelleybluebookimages.com/kbb/base...,0.0,0.0
19842,volvo,c70,2010,C70 T5 Convertible 2D,Gas,FWD,19,28,22,Automatic,8125,8125,https://file.kelleybluebookimages.com/kbb/base...,0.0,0.0

In [15]:
makes = all_mm.make.unique()
models = all_mm.model.unique()
trims = all_mm.trim.unique()
fuel_types = all_mm.fuel_type.unique()
drivetrains = all_mm.drivetrain.unique()
images = all_mm.image.unique()


makes2 = {}
count = 1
for m in makes:
    makes2[m] = count
    count += 1

models2 = {}
count = 1
for m in models:
    models2[m] = count
    count += 1

trims2 = {}
count = 1
for t in trims:
    trims2[t] = count
    count += 1

fuel_types2 = {}
count = 1
for ft in fuel_types:
    fuel_types2[ft] = count
    count += 1

drivetrains2 = {}
count = 1
for dt in drivetrains:
    drivetrains2[dt] = count
    count += 1

images2 = {}
count = 1
for image in images:
    images2[image] = count
    count += 1

images2

{'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53604/2024-Acura-RDX-front_53604_032_1671x782_SI_cropped.png?downsize=750:*': 1,
 'https://cdn.jwplayer.com/v2/media/Wv7dF60J/poster.jpg': 2,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53161/2024-Acura-MDX-front_53161_032_1710x797_RE_cropped.png?downsize=750:*': 3,
 'https://cdn.jwplayer.com/v2/media/NLfHCN7W/poster.jpg': 4,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/51840/2024-Acura-TLX-front_51840_032_1822x728_GR_cropped.png?downsize=750:*': 5,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/52060/2023-Acura-RDX-front_52060_032_1671x782_RE_cropped.png?downsize=750:*': 6,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/51006/2023-Acura-MDX-front_51006_032_1845x843_RE_cropped.png?downsize=750:*': 7,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/51840/2023-Acura-TLX-front_51840_032_1822x728_BV_cropped.png?downsize=750:*': 8,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/15173/2022-Acura-RDX-front_15173_032_1672x782_BV_cropped.png?downsize=750:*': 9,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/15124/2022-Acura-MDX-front_15124_032_1834x827_BX_cropped.png?downsize=750:*': 10,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/13357/2022-Acura-ILX-front_13357_032_1841x765_WV_cropped.png?downsize=750:*': 11,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/14477/2022-Acura-TLX-front_14477_032_1827x718_GY_cropped.png?downsize=750:*': 12,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/50711/2022-Acura-NSX-front_50711_032_1847x654_RL_cropped.png?downsize=750:*': 13,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12860/2021-Acura-RDX-front_12860_032_1834x858_RV_cropped.png?downsize=750:*': 14,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/13357/2021-Acura-ILX-front_13357_032_1841x765_RE_cropped.png?downsize=750:*': 15,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/14966/2021-Acura-TLX-front_14966_032_1822x728_SI_cropped.png?downsize=750:*': 16,
 'https://file.kelleybluebookimages.com/kbb/base/house/2021/2021-Acura-NSX-FrontSide_ACNSX2101_640x480.jpg?downsize=750:*': 17,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12361/2020-Acura-MDX-front_12361_032_1842x849_SI_cropped.png?downsize=750:*': 18,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12875/2020-Acura-RDX-front_12875_032_1827x852_BM_cropped.png?downsize=750:*': 19,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/13221/2020-Acura-ILX-front_13221_032_1837x765_WV_cropped.png?downsize=750:*': 20,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12106/2020-Acura-TLX-front_12106_032_1836x760_RE_cropped.png?downsize=750:*': 21,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12480/2020-Acura-RLX-front_12480_032_1831x722_BZ_cropped.png?downsize=750:*': 22,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12568/2020-Acura-RLX%20Sport%20Hybrid-front_12568_032_1834x729_BS_cropped.png?downsize=750:*': 23,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12992/2020-Acura-MDX%20Sport%20Hybrid-front_12992_032_1846x845_BT_cropped.png?downsize=750:*': 24,
 'https://file.kelleybluebookimages.com/kbb/base/house/2020/2020-Acura-NSX-FrontSide_ACNSX2001_640x480.jpg?downsize=750:*': 25,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/13357/2019-Acura-ILX-front_13357_032_1841x765_WV_cropped.png?downsize=750:*': 26,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12069/2019-Acura-TLX-front_12069_032_1840x741_RF_cropped.png?downsize=750:*': 27,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12480/2019-Acura-RLX-front_12480_032_1831x722_BZ_cropped.png?downsize=750:*': 28,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12568/2019-Acura-RLX%20Sport%20Hybrid-front_12568_032_1834x729_RX_cropped.png?downsize=750:*': 29,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/13955/2019-Acura-MDX-front_13955_032_1847x870_GN_cropped.png?downsize=750:*': 30,
 'https://file.kelleybluebookimages.com/kbb/base/house/2019/2019-Acura-MDX%20Sport%20Hybrid-FrontSide_ATMDXSH1901_640x480.jpg?downsize=750:*': 31,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/13000/2019-Acura-RDX-front_13000_032_1834x853_BC_cropped.png?downsize=750:*': 32,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/11810/2019-Acura-NSX-front_11810_032_1827x688_RH_cropped.png?downsize=750:*': 33,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12083/2018-Acura-RDX-front_12083_032_1863x871_RB_cropped.png?downsize=750:*': 34,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/11219/2018-Acura-ILX-front_11219_032_1819x761_SI_cropped.png?downsize=750:*': 35,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12480/2018-Acura-RLX-front_12480_032_1831x722_BZ_cropped.png?downsize=750:*': 36,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12568/2018-Acura-RLX%20Sport%20Hybrid-front_12568_032_1834x729_RX_cropped.png?downsize=750:*': 37,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12057/2018-Acura-TLX-front_12057_032_1830x743_BV_cropped.png?downsize=750:*': 38,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12361/2018-Acura-MDX-front_12361_032_1842x849_SI_cropped.png?downsize=750:*': 39,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12992/2018-Acura-MDX%20Sport%20Hybrid-front_12992_032_1846x845_BK_cropped.png?downsize=750:*': 40,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/11810/2018-Acura-NSX-front_11810_032_1827x688_RH_cropped.png?downsize=750:*': 41,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/11340/2017-Acura-RDX-front_11340_032_1864x873_SX_cropped.png?downsize=750:*': 42,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/10421/2017-Acura-ILX-front_10421_032_1825x752_SX_cropped.png?downsize=750:*': 43,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/11937/2017-Acura-TLX-front_11937_032_1837x747_GY_cropped.png?downsize=750:*': 44,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12031/2017-Acura-RLX-front_12031_032_1834x733_GR_cropped.png?downsize=750:*': 45,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/11150/2017-Acura-RLX%20Sport%20Hybrid-front_11150_032_1829x735_SI_cropped.png?downsize=750:*': 46,
 'https://file.kelleybluebookimages.com/kbb/base/house/2017/2017-Acura-MDX%20Sport%20Hybrid-FrontSide_ATMDXSH1701_640x480.jpg?downsize=750:*': 47,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/11319/2017-Acura-MDX-front_11319_032_1845x859_GX_cropped.png?downsize=750:*': 48,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/11810/2017-Acura-NSX-front_11810_032_1827x688_RH_cropped.png?downsize=750:*': 49,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/10335/2016-Acura-MDX-front_10335_032_1880x853_RX_cropped.png?downsize=750:*': 50,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/10469/2016-Acura-RDX-front_10469_032_1853x857_BX_cropped.png?downsize=750:*': 51,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/10421/2016-Acura-ILX-front_10421_032_1825x752_SX_cropped.png?downsize=750:*': 52,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/10030/2016-Acura-TLX-front_10030_032_1847x758_BL_cropped.png?downsize=750:*': 53,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/10364/2016-Acura-RLX-front_10364_032_1841x731_GR_cropped.png?downsize=750:*': 54,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/11150/2016-Acura-RLX%20Sport%20Hybrid-front_11150_032_1829x735_BZ_cropped.png?downsize=750:*': 55,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/9027/2015-Acura-MDX-front_9027_032_1870x863_SA_cropped.png?downsize=750:*': 56,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/9775/2015-Acura-RLX-front_9775_032_1844x733_BX_cropped.png?downsize=750:*': 57,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/10293/2015-Acura-RDX-front_10293_032_1880x862_BK_cropped.png?downsize=750:*': 58,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/9776/2015-Acura-ILX-front_9776_032_1829x775_SA_cropped.png?downsize=750:*': 59,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/10030/2015-Acura-TLX-front_10030_032_1847x758_BL_cropped.png?downsize=750:*': 60,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/9027/2014-Acura-MDX-front_9027_032_1870x863_SA_cropped.png?downsize=750:*': 61,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/8816/2014-Acura-RLX-front_8816_032_1825x732_SA_cropped.png?downsize=750:*': 62,
 'https://file.kelleybluebookimages.com/kbb/base/house/2014/2014-Acura-RLX%20Sport%20Hybrid-FrontSide_ACRLXSHH1401_640x480.jpg?downsize=750:*': 63,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/9327/2014-Acura-TSX-front_9327_032_1804x743_BV_cropped.png?downsize=750:*': 64,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/8868/2014-Acura-RDX-front_8868_032_1869x869_RB_cropped.png?downsize=750:*': 65,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/9243/2014-Acura-TL-front_9243_032_1812x738_SA_cropped.png?downsize=750:*': 66,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/9113/2014-Acura-ILX-front_9113_032_1816x765_RX_cropped.png?downsize=750:*': 67,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/8132/2013-Acura-RDX-front_8132_032_1856x865_BS_cropped.png?downsize=750:*': 68,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/8549/2013-Acura-MDX-front_8549_032_1855x887_BL_cropped.png?downsize=750:*': 69,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/8683/2013-Acura-TL-front_8683_032_1820x742_GR_cropped.png?downsize=750:*': 70,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/8548/2013-Acura-TSX-front_8548_032_1809x751_BV_cropped.png?downsize=750:*': 71,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/8354/2013-Acura-ILX-front_8354_032_1819x774_GY_cropped.png?downsize=750:*': 72,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/8779/2013-Acura-ZDX-front_8779_032_1834x816_BK_cropped.png?downsize=750:*': 73,
 'https://file.kelleybluebookimages.com/kbb/base/house/2012/2012-Acura-MDX-FrontSide_ATMDX121_640x480.jpg?downsize=750:*': 74,
 'https://file.kelleybluebookimages.com/kbb/base/house/2012/2012-Acura-TSX-FrontSide_ACTSX121_640x480.jpg?downsize=750:*': 75,
 'https://file.kelleybluebookimages.com/kbb/base/house/2012/2012-Acura-TL-FrontSide_ACTL121_640x480.jpg?downsize=750:*': 76,
 'https://file.kelleybluebookimages.com/kbb/base/house/2012/2012-Acura-ZDX-FrontSide_ATZDX121_640x480.jpg?downsize=750:*': 77,
 'https://file.kelleybluebookimages.com/kbb/base/house/2012/2012-Acura-RDX-FrontSide_ATRDX121_640x480.jpg?downsize=750:*': 78,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/8145/2012-Acura-RL-front_8145_032_1802x732_SI_cropped.png?downsize=750:*': 79,
 'https://file.kelleybluebookimages.com/kbb/base/house/2011/2011-Acura-TSX-FrontSide_ACTSX111_640x480.jpg?downsize=750:*': 80,
 'https://file.kelleybluebookimages.com/kbb/base/house/2011/2011-Acura-TL-FrontSide_ACTL111_640x480.jpg?downsize=750:*': 81,
 'https://file.kelleybluebookimages.com/kbb/base/house/2011/2011-Acura-RL-FrontSide_ACRL111_640x480.jpg?downsize=750:*': 82,
 'https://file.kelleybluebookimages.com/kbb/base/house/2011/2011-Acura-RDX-FrontSide_ATRDX111_505x375.jpg?downsize=750:*': 83,
 'https://file.kelleybluebookimages.com/kbb/base/house/2011/2011-Acura-MDX-FrontSide_ATMDX111_640x480.jpg?downsize=750:*': 84,
 'https://file.kelleybluebookimages.com/kbb/base/house/2011/2011-Acura-ZDX-FrontSide_ATZDX111_640x480.jpg?downsize=750:*': 85,
 'https://file.kelleybluebookimages.com/kbb/base/house/2010/2010-Acura-TL-FrontSide_ACTL101_505x375.jpg?downsize=750:*': 86,
 'https://file.kelleybluebookimages.com/kbb/base/house/2010/2010-Acura-MDX-FrontSide_ATMDX101_505x375.jpg?downsize=750:*': 87,
 'https://file.kelleybluebookimages.com/kbb/base/house/2010/2010-Acura-RL-FrontSide_ACRL101_505x375.jpg?downsize=750:*': 88,
 'https://file.kelleybluebookimages.com/kbb/base/house/2010/2010-Acura-TSX-FrontSide_ACTSX101_505x375.jpg?downsize=750:*': 89,
 'https://file.kelleybluebookimages.com/kbb/base/house/2010/2010-Acura-RDX-FrontSide_ATRDX101_505x375.jpg?downsize=750:*': 90,
 'https://file.kelleybluebookimages.com/kbb/base/house/2010/2010-Acura-ZDX-FrontSide_ATZDX101_505x375.jpg?downsize=750:*': 91,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/54324/2024-Audi-A3-front_54324_032_1644x690_T9T9_cropped.png?downsize=750:*': 92,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53298/2024-Audi-Q3-front_53298_032_1825x856_L5L5_cropped.png?downsize=750:*': 93,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/52928/2024-Audi-Q7-front_52928_032_1841x827_2D2D_cropped.png?downsize=750:*': 94,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53488/2024-Audi-A7-front_53488_032_1834x710_5U5U_cropped.png?downsize=750:*': 95,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53974/2024-Audi-SQ7-front_53974_032_1835x818_2Y2Y_cropped.png?downsize=750:*': 96,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/14708/2024-Audi-Q5-front_14708_032_1845x859_2D2D_cropped.png?downsize=750:*': 97,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53843/2024-Audi-Q4%20e-tron-front_53843_032_1834x842_0E_cropped.png?downsize=750:*': 98,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53849/2024-Audi-Q5%20Sportback-front_53849_032_1826x835_M4M4_cropped.png?downsize=750:*': 99,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53844/2024-Audi-Q4%20Sportback%20e-tron-front_53844_032_1833x844_2Y2Y_cropped.png?downsize=750:*': 100,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/54092/2024-Audi-A6-front_54092_032_1656x661_Z7Z7_cropped.png?downsize=750:*': 101,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/54270/2024-Audi-A8-front_54270_032_1642x636_R5R5_cropped.png?downsize=750:*': 102,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53444/2024-Audi-S8-front_53444_032_1760x692_2Y2Y_cropped.png?downsize=750:*': 103,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/15564/2024-Audi-A4-front_15564_032_1824x743_L5L5_cropped.png?downsize=750:*': 104,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53450/2024-Audi-A5-front_53450_032_1815x727_M4M4_cropped.png?downsize=750:*': 105,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/14431/2024-Audi-A4%20allroad-front_14431_032_1814x775_2D2D_cropped.png?downsize=750:*': 106,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/54009/2024-Audi-S5-front_54009_032_1820x721_Z9Z9_cropped.png?downsize=750:*': 107,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/54008/2024-Audi-RS%205-front_54008_032_1813x726_2D2D_cropped.png?downsize=750:*': 108,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53487/2024-Audi-A6%20allroad-front_53487_032_1800x735_2Y2Y_cropped.png?downsize=750:*': 109,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/54630/2024-Audi-Q8-front_54630_032_1847x840_2Z2Z_cropped.png?downsize=750:*': 110,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53980/2024-Audi-SQ8-front_53980_032_1850x820_0E0E_cropped.png?downsize=750:*': 111,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53982/2024-Audi-RS%20Q8-front_53982_032_1841x825_6Y6Y_cropped.png?downsize=750:*': 112,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/54354/2024-Audi-e-tron%20GT-front_54354_032_1651x635_Y1Y1_cropped.png?downsize=750:*': 113,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/52703/2024-Audi-Q8%20e-tron-front_52703_032_1846x791_3D3D_cropped.png?downsize=750:*': 114,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53494/2024-Audi-Q8%20Sportback%20e-tron-front_53494_032_1819x787_9E9E_cropped.png?downsize=750:*': 115,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53300/2024-Audi-S3-front_53300_032_1807x761_T9T9_cropped.png?downsize=750:*': 116,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/54003/2024-Audi-S4-front_54003_032_1813x737_2Y2Y_cropped.png?downsize=750:*': 117,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/54046/2024-Audi-SQ5-front_54046_032_1842x845_Z7Z7_cropped.png?downsize=750:*': 118,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/15066/2024-Audi-SQ5%20Sportback-front_15066_032_1868x848_M4M4_cropped.png?downsize=750:*': 119,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/54000/2024-Audi-RS%203-front_54000_032_1814x758_0E0E_cropped.png?downsize=750:*': 120,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/54043/2024-Audi-S6-front_54043_032_1827x719_S5S5_cropped.png?downsize=750:*': 121,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/51526/2024-Audi-S7-front_51526_032_1816x711_A2A2_cropped.png?downsize=750:*': 122,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53980/2024-Audi-SQ8%20e-tron-front_53980_032_1850x820_2Y2Y_cropped.png?downsize=750:*': 123,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/54047/2024-Audi-SQ8%20Sportback%20e-tron-front_54047_032_1819x787_G5G5_cropped.png?downsize=750:*': 124,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53247/2024-Audi-RS%206-front_53247_032_1799x727_R5R5_cropped.png?downsize=750:*': 125,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53251/2024-Audi-RS%207-front_53251_032_1799x692_R5R5_cropped.png?downsize=750:*': 126,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/54050/2024-Audi-RS%20e-tron%20GT-front_54050_032_1786x691_T9T9_cropped.png?downsize=750:*': 127,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/50687/2023-Audi-A3-front_50687_032_1852x773_H1H1_cropped.png?downsize=750:*': 128,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/51427/2023-Audi-Q3-front_51427_032_1825x856_G3G3_cropped.png?downsize=750:*': 129,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/50361/2023-Audi-A5-front_50361_032_1823x737_Y1Y1_cropped.png?downsize=750:*': 130,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/52928/2023-Audi-Q7-front_52928_032_1841x828_D6D6_cropped.png?downsize=750:*': 131,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/51475/2023-Audi-A7-front_51475_032_1834x710_T9T9_cropped.png?downsize=750:*': 132,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/53965/2023-Audi-A4-front_53965_032_1631x658_T9T9_cropped.png?downsize=750:*': 133,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/51524/2023-Audi-Q4%20e-tron-front_51524_032_1834x842_0E0E_cropped.png?downsize=750:*': 134,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/14708/2023-Audi-Q5-front_14708_032_1845x859_2Y2Y_cropped.png?downsize=750:*': 135,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/51426/2023-Audi-Q5%20Sportback-front_51426_032_1826x835_6I6I_cropped.png?downsize=750:*': 136,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/14731/2023-Audi-SQ5-front_14731_032_1842x845_T9T9_cropped.png?downsize=750:*': 137,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/52208/2023-Audi-SQ5%20Sportback-front_52208_032_1862x836_0E0E_cropped.png?downsize=750:*': 138,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/51521/2023-Audi-A4%20allroad-front_51521_032_1813x775_2D2D_cropped.png?downsize=750:*': 139,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/51396/2023-Audi-A6-front_51396_032_1799x735_0E0E_cropped.png?downsize=750:*': 140,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/51535/2023-Audi-R8-front_51535_032_1848x697_8R8R_cropped.png?downsize=750:*': 141,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/51499/2023-Audi-Q8-front_51499_032_1844x841_0Q0Q_cropped.png?downsize=750:*': 142,
 'https://file.kelleybluebookimages.com/kbb/base/evox/CP/51399/2023-Audi-A6%20allroad-front_51399_032_1810x743_Z7Z7_cropped.png?downsize=750:*': 143,

In [17]:
all_mm["make_id"] = None
all_mm["model_id"] = None
all_mm["trim_id"] = None
all_mm["fuel_type_id"] = None
all_mm["drivetrain_id"] = None
all_mm["image_id"] = None

def set_ids(row):
    row["make_id"] = makes2[row["make"]]
    row["model_id"] = models2[row["model"]]
    row["trim_id"] = trims2[row["trim"]]
    row["fuel_type_id"] = fuel_types2[row["fuel_type"]]
    row["drivetrain_id"] = drivetrains2[row["drivetrain"]]
    row["image_id"] = images2[row["image"]]
    return row

all_mm2 = all_mm.apply(set_ids, axis=1)
all_mm2

,make,model,year,trim,fuel_type,drivetrain,city_fuel_economy,hwy_fuel_economy,comb_fuel_economy,transmission_type,...,med_price,image,expert_score,consumer_score,make_id,model_id,trim_id,fuel_type_id,drivetrain_id,image_id
0,acura,rdx,2024,RDX SH-AWD,Gas,AWD,21,27,23,Automatic,...,51350,https://file.kelleybluebookimages.com/kbb/base...,4.6,3.9,1,1,1,1,1,1
1,acura,rdx,2024,RDX SH-AWD w/Technology Pkg,Gas,AWD,21,27,23,Automatic,...,51350,https://file.kelleybluebookimages.com/kbb/base...,4.6,3.9,1,1,2,1,1,1
2,acura,rdx,2024,RDX SH-AWD w/A-Spec Pkg,Gas,AWD,21,27,23,Automatic,...,51350,https://file.kelleybluebookimages.com/kbb/base...,4.6,3.9,1,1,3,1,1,1
3,acura,rdx,2024,RDX SH-AWD w/Advance Pkg,Gas,AWD,21,27,23,Automatic,...,51350,https://file.kelleybluebookimages.com/kbb/base...,4.6,3.9,1,1,4,1,1,1
4,acura,rdx,2024,RDX SH-AWD w/A-Spec & Advance Pkgs,Gas,AWD,21,26,23,Automatic,...,51350,https://file.kelleybluebookimages.com/kbb/base...,4.6,3.9,1,1,5,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19838,volvo,xc70,2010,Wagon 4D,Gas,AWD,16,22,18,Automatic,...,6990,https://file.kelleybluebookimages.com/kbb/base...,0.0,0.0,26,694,6128,1,1,4957
19839,volvo,xc70,2010,XC70 T6 Wagon 4D,Gas,AWD,16,21,18,Automatic,...,6990,https://file.kelleybluebookimages.com/kbb/base...,0.0,0.0,26,694,6177,1,1,4957
19840,volvo,c30,2010,D,Gas,FWD,21,29,24,Manual,...,7654,https://file.kelleybluebookimages.com/kbb/base...,0.0,0.0,26,697,52,1,2,4958
19841,volvo,c30,2010,D,Gas,FWD,21,29,24,Manual,...,7654,https://file.kelleybluebookimages.com/kbb/base...,0.0,0.0,26,697,52,1,2,4958
19842,volvo,c70,2010,C70 T5 Convertible 2D,Gas,FWD,19,28,22,Automatic,...,8125,https://file.kelleybluebookimages.com/kbb/base...,0.0,0.0,26,696,6216,1,2,4959

In [20]:
all_mm2.to_csv("all_makes_models_complete.csv", index=False)